import os
import re

# Targeted directories
ROOT_DIR = r"c:\Users\ADMIN\Desktop\pdfjin\frontend"
TARGET_DIRS = [
    os.path.join(ROOT_DIR, "js"),
    os.path.join(ROOT_DIR, "pages"),
]

# Common patterns to fix
SIMPLE_REPLACEMENTS = {
    'JSON.parseeeee': 'JSON.parse',
    'JSON.parse (': 'JSON.parse(',
    'JSON.stringify (': 'JSON.stringify(',
    'loadsript': 'loadScript',
    'ssc: =': 's.src =',
    'sonload: =': 's.onload =',
    'reslve()': 'resolve()',
    'Promis(': 'Promise(',
    'applyPersnalization': 'applyPersonalization',
    'stupDeveloperdashboard': 'setupDeveloperDashboard',
    'verson': 'version',
    'sat-': 'stat-',
    'sat_': 'stat_',
    'prousers': 'proUsers',
    'entusers': 'entUsers',
    'allUsersfilter': 'allUsers.filter',
    'allUsersfind': 'allUsers.find',
    'allUserslength': 'allUsers.length',
    'userslength': 'users.length',
    'keyslength': 'keys.length',
    'itemslength': 'items.length',
    'MSSmap': 'MSS.map',
    'MSS.map': 'mss.map', # Based on local var mss
    'MSS': 'mss',
    'MSs': 'mss',
    'MSsmap': 'mss.map',
    'namesmap': 'names.map',
    'domainslength': 'domains.length',
    'tierslength': 'tiers.length',
    'statusslength': 'statuss.length',
    'generatesles': 'generateSales',
    'resltspus': 'results.push',
    'slesmap': 'sales.map',
    'generatesles': 'generateSales',
    'generatesles(': 'generateSales(',
    'generateusers': 'generateUsers',
    'generateActivity': 'generateActivity',
    'generateLogs': 'generateLogs',
    'toLocaleDatesring': 'toLocaleDateString',
    'toLocaleTimesring': 'toLocaleTimeString',
    'en-Us': 'en-US',
    'input.focus);': 'input.focus();',
    'btnsave': 'btnSave',
    'btnsve': 'btnSave',
    'btnSave.textContent': 'btnSave.textContent',
    'btnSave.disabled': 'btnSave.disabled',
    'disount': 'discount',
    'Pasword': 'Password',
    'pasword': 'password',
    'pas': 'pass',
    'Pas': 'Pass',
    'sre': 'sure',
    'sve': 'save',
    'sncsession': 'syncSession',
    'loadDasData': 'loadDashboardData',
    'updatePricingdisplay': 'updatePricingDisplay',
    'limitFreeTasks': 'limitFreeTasks',
    'limitFreesize': 'limitFreeSize',
    'limitProTasks': 'limitProTasks',
    'limitProsize': 'limitProSize',
    'limitEntTasks': 'limitEntTasks',
    'limitEntsize': 'limitEntSize',
    'priceProMonthlyVal': 'priceProMonthlyVal',
    'priceProYearlyVal': 'priceProYearlyVal',
    'priceProMonthlyBtn': 'priceProMonthlyBtn',
    'priceProYearlyBtn': 'priceProYearlyBtn',
    'priceEntMonthlyInput': 'priceEntMonthlyInput',
    'priceEntYearlyInput': 'priceEntYearlyInput',
    'proTasLimit': 'proTaskLimit',
    'proLimitsize': 'proLimitSize',
    'entLimitsize': 'entLimitSize',
    'freeLimitTasks': 'freeLimitTasks',
    'freeLimitsize': 'freeLimitSize',
    'api-keystoken': 'api-keys?token',
    'api-keysgenerate': 'api-keys/generate',
    'apiKeysuccess': 'apiKeySuccess',
    'newKeydisplay': 'newKeyDisplay',
    'copystatus': 'copyStatus',
    'apiUsgeCount': 'apiUsageCount',
    'apiUsgeBar': 'apiUsageBar',
    'smple': 'simple',
    'sctions': 'sections',
    'sction': 'section',
    'sdebar': 'sidebar',
    'sitch': 'switch',
    'stTool': 'setTool',
    'st-': 'set-',
    'closs': 'closest',
    'json (': 'JSON.stringify(',
    'json: (': 'JSON.stringify(',
    'JSON.stringify (': 'JSON.stringify(',
    'parseeeee': 'parse',
    'vslas': 'vs last',
    'refres': 'refresh',
    'status u': 'status: u',
    'status active': 'status-active',
    'status ssended': 'status-suspended',
    'ssended': 'suspended',
    'scCurrentPas': 'scCurrentPass',
    'scNewPas': 'scNewPass',
    'scConfirmPas': 'scConfirmPass',
    'password srength': 'password strength',
    'checksrength': 'checkStrength',
    'srengthFill': 'strengthFill',
    'srengthLabel': 'strengthLabel',
    'levelse': 'levels =',
    'levelse0]': 'levels[0]',
    'levelseMath': 'levels[Math',
    'paswordFeedback': 'passwordFeedback',
    'pasLasChanged': 'passLastChanged',
    'svedPasDate': 'savedPassDate',
    'btnsendTesEmail': 'btnSendTestEmail',
    'teamLis': 'teamList',
    'inviteEmail': 'inviteEmail',
    'inviteRole': 'inviteRole',
    'teamFeedback': 'teamFeedback',
    'teamOwnerName': 'teamOwnerName',
    'teamOwnerEmail': 'teamOwnerEmail',
    'wsettings': 'workspaceSettings',
    'wsame': 'wsName',
    'wsLanguage': 'wsLanguage',
    'wsutputFormat': 'wsOutputFormat',
    'wsetention': 'wsRetention',
    'wsuality': 'wsQuality',
    'notifTas': 'notifTasks',
    'notifTeam': 'notifTeam',
    'notifProduct': 'notifProduct',
    'settingseedback': 'settingsFeedback',
    'btnsvesettings': 'btnSaveSettings',
    'dasToolCards': 'dasToolCards',
    'toolFilterBtns': 'toolFilterBtns',
    'profileEmaildisplay': 'profileEmailDisplay',
    'scurityEmail': 'securityEmail',
}

REGEX_REPLACEMENTS = [
    (r': =', r'='),
    (r'link: \.', r'link.'),
    (r'link \.', r'link.'),
    (r's\.opacity', r's.style.opacity'),
    (r's\.pointerEvents', r's.style.pointerEvents'),
    (r's\.display', r's.style.display'),
    (r's\.visibility', r's.style.visibility'),
    (r's\.opacity', r's.style.opacity'),
    (r's\.height', r's.style.height'),
    (r's\.width', r's.style.width'),
    (r's\.background', r's.style.background'),
    (r's\.color', r's.style.color'),
    (r's\.marginTop', r's.style.marginTop'),
    (r's\.paddingTop', r's.style.paddingTop'),
    (r's\.cursor', r's.style.cursor'),
    (r's\.pointerEvents', r's.style.pointerEvents'),
    (r's\.overflow', r's.style.overflow'),
    (r's\.marginLeft', r's.style.marginLeft'),
    (r's\.marginRight', r's.style.marginRight'),
    (r's\.zIndex', r's.style.zIndex'),
    (r's\.filter', r's.style.filter'),
    (r's\.textAlign', r's.style.textAlign'),
    (r's\.borderRadius', r's.style.borderRadius'),
    (r's\.boxShadow', r's.style.boxShadow'),
    (r's\.fontSize', r's.style.fontSize'),
    (r's\.fontWeight', r's.style.fontWeight'),
    (r's\.lineHeight', r's.style.lineHeight'),
    (r's\.letterSpacing', r's.style.letterSpacing'),
    (r's\.borderColor', r's.style.borderColor'),
    (r's\.borderBottom', r's.style.borderBottom'),
    (r's\.borderTop', r's.style.borderTop'),
    (r's\.border', r's.style.border'),
    (r's\.transition', r's.style.transition'),
    (r's\.flex', r's.style.flex'),
    (r's\.alignItems', r's.style.alignItems'),
    (r's\.justifyContent', r's.style.justifyContent'),
    (r's\.gap', r's.style.gap'),
    (r's\.padding', r's.style.padding'),
    (r's\.margin', r's.style.margin'),
    (r's\.top', r's.style.top'),
    (r's\.left', r's.style.left'),
    (r's\.right', r's.style.right'),
    (r's\.bottom', r's.style.bottom'),
    (r's\.position', r's.style.position'),
    (r's\.whiteSpace', r's.style.whiteSpace'),
    (r's\.overflowX', r's.style.overflowX'),
    (r's\.overflowY', r's.style.overflowY'),
    (r's\.textDecoration', r's.style.textDecoration'),
    (r's\.listStyle', r's.style.listStyle'),
    (r's\.listStyleType', r's.style.listStyleType'),
    (r's\.boxSizing', r's.style.boxSizing'),
    (r's\.outline', r's.style.outline'),
    (r's\.userSelect', r's.style.userSelect'),
    (r's\.appearance', r's.style.appearance'),
    (r's\.setProperty', r's.style.setProperty'),
    (r's\.getPropertyValue', r's.style.getPropertyValue'),
    (r's\.removeProperty', r's.style.removeProperty'),
    (r's\.className', r's.className'),
    (r's\.classList', r's.classList'),
    (r's\.id', r's.id'),
    (r's\.value', r's.value'),
    (r's\.checked', r's.checked'),
    (r's\.disabled', r's.disabled'),
    (r's\.innerHTML', r's.innerHTML'),
    (r's\.textContent', r's.textContent'),
    (r's\.innerText', r's.innerText'),
    (r's\.getAttribute', r's.getAttribute'),
    (r's\.setAttribute', r's.setAttribute'),
    (r's\.removeAttribute', r's.removeAttribute'),
    (r's\.hasAttribute', r's.hasAttribute'),
    (r's\.append', r's.append'),
    (r's\.appendChild', r's.appendChild'),
    (r's\.prepend', r's.prepend'),
    (r's\.remove', r's.remove'),
    (r's\.replaceWith', r's.replaceWith'),
    (r's\.scrollIntoView', r's.scrollIntoView'),
    (r's \.background', r's.style.background'),
    (r'l \.classList', r'l.classList'),
    (r'l \.toggle', r'l.classList.toggle'),
    (r'l \.add', r'l.classList.add'),
    (r'l \.remove', r'l.classList.remove'),
    (r'l \.contains', r'l.classList.contains'),
    (r'l \.getAttribute', r'l.getAttribute'),
    (r'l \.setAttribute', r'l.setAttribute'),
    (r'l \.target', r'l.target'),
    (r'l \.tagName', r'l.tagName'),
    (r'l \.id', r'l.id'),
    (r'l \.className', r'l.className'),
    (r'l \.value', r'l.value'),
    (r'l \.textContent', r'l.textContent'),
    (r'l \.innerHTML', r'l.innerHTML'),
    (r'l \.style', r'l.style'),
    (r'l \.disabled', r'l.disabled'),
    (r'l \.style\.display', r'l.style.display'),
    (r'l \.style\.opacity', r'l.style.opacity'),
    (r'([a-zA-Z0-9]+)forEach', r'\1.forEach'),
    (r'([a-zA-Z0-9]+)map', r'\1.map'),
    (r'([a-zA-Z0-9]+)sort', r'\1.sort'),
    (r'([a-zA-Z0-9]+)filter', r'\1.filter'),
    (r'([a-zA-Z0-9]+)find', r'\1.find'),
    (r'([a-zA-Z0-9]+)reduce', r'\1.reduce'),
    (r'([a-zA-Z0-9]+)every', r'\1.every'),
    (r'([a-zA-Z0-9]+)some', r'\1.some'),
    (r'([a-zA-Z0-9]+)includes', r'\1.includes'),
    (r'([a-zA-Z0-9]+)split', r'\1.split'),
    (r'([a-zA-Z0-9]+)join', r'\1.join'),
    (r'([a-zA-Z0-9]+)slice', r'\1.slice'),
    (r'([a-zA-Z0-9]+)substring', r'\1.substring'),
    (r'([a-zA-Z0-9]+)toLowerCase', r'\1.toLowerCase'),
    (r'([a-zA-Z0-9]+)toUpperCase', r'\1.toUpperCase'),
    (r'([a-zA-Z0-9]+)trim', r'\1.trim'),
    (r'([a-zA-Z0-9]+)push', r'\1.push'),
    (r'([a-zA-Z0-9]+)pop', r'\1.pop'),
    (r'([a-zA-Z0-9]+)shift', r'\1.shift'),
    (r'([a-zA-Z0-9]+)unshift', r'\1.unshift'),
    (r'([a-zA-Z0-9]+)indexOf', r'\1.indexOf'),
    (r'([a-zA-Z0-9]+)lastIndexOf', r'\1.lastIndexOf'),
    (r'([a-zA-Z0-9]+)replace', r'\1.replace'),
    (r'([a-zA-Z0-9]+)match', r'\1.match'),
    (r'([a-zA-Z0-9]+)test', r'\1.test'),
    (r'([a-zA-Z0-9]+)search', r'\1.search'),
    (r'([a-zA-Z0-9]+)scrollIntoView', r'\1.scrollIntoView'),
    (r'([a-zA-Z0-9]+)focus', r'\1.focus'),
    (r'([a-zA-Z0-9]+)select', r'\1.select'),
    (r'([a-zA-Z0-9]+)click', r'\1.click'),
    (r'([a-zA-Z0-9]+)submit', r'\1.submit'),
    (r'([a-zA-Z0-9]+)reset', r'\1.reset'),
    (r'([a-zA-Z0-9]+)addEventListener', r'\1.addEventListener'),
    (r'([a-zA-Z0-9]+)removeEventListener', r'\1.removeEventListener'),
    (r'([a-zA-Z0-9]+)dispatchEvent', r'\1.dispatchEvent'),
    (r'([a-zA-Z0-9]+)get', r'\1.get'),
    (r'([a-zA-Z0-9]+)set', r'\1.set'),
    (r'([a-zA-Z0-9]+)has', r'\1.has'),
    (r'([a-zA-Z0-9]+)delete', r'\1.delete'),
    (r'([a-zA-Z0-9]+)clear', r'\1.clear'),
    (r'([a-zA-Z0-9]+)keys', r'\1.keys'),
    (r'([a-zA-Z0-9]+)values', r'\1.values'),
    (r'([a-zA-Z0-9]+)entries', r'\1.entries'),
    (r'([a-zA-Z0-9]+)all', r'\1.all'),
    (r'([a-zA-Z0-9]+)race', r'\1.race'),
    (r'([a-zA-Z0-9]+)any', r'\1.any'),
    (r'([a-zA-Z0-9]+)allSettled', r'\1.allSettled'),
    (r'([a-zA-Z0-9]+)then', r'\1.then'),
    (r'([a-zA-Z0-9]+)catch', r'\1.catch'),
    (r'([a-zA-Z0-9]+)finally', r'\1.finally'),
]

def fix_file(file_path):
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
    
    # Apply simple replacements
    for old, new in SIMPLE_REPLACEMENTS.items():
        content = content.replace(old, new)
    
    # Apply regex replacements
    for pattern, replacement in REGEX_REPLACEMENTS:
        content = re.sub(pattern, replacement, content)

    # Specific fix for dash-isolated/dashboard-body issue
    if "dashboard-body" in content and "index.html" in file_path:
         content = content.replace('class="dashboard-body"', 'class="landing-page"')

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Fixed: {file_path}")

def main():
    for target in TARGET_DIRS:
        for root, dirs, files in os.walk(target):
            for file in files:
                if file.endswith(('.html', '.js', '.css')):
                    fix_file(os.path.join(root, file))

    # Also fix index.html in root
    fix_file(os.path.join(ROOT_DIR, "index.html"))

if __name__ == "__main__":
    main()
